Repository AY2324S2-CS2103T-F13-3/tp, pull requests merged in 2024-03, with the labels that each got.

#40 Modify the README.md and AboutUs.md, previous pull request failed tests
  README.md
  docs/AboutUs.md
  docs/images/ivan24004.png
  docs/images/ryan-reno.png
Labels: documentation

#69 Add stub for a QueryableCourseMate
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/coursemate/QueryableCourseMate.java
  src/main/java/seedu/address/model/coursemate/UniqueCourseMateList.java
  src/main/java/seedu/address/model/coursemate/exceptions/IllegalQueryableParameterException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/coursemate/QueryableCourseMateTest.java
  src/test/java/seedu/address/model/coursemate/UniqueCourseMateListTest.java
Labels: enhancement

#99 Fix invalid hashtag notation and allow substring reference
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddMemberCommand.java
  src/main/java/seedu/address/logic/commands/AddSkillCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMemberCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSkillCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ContactList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/coursemate/UniqueCourseMateList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSkillCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSkillCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteSkillCommandParserTest.java
Labels: bug

#97 Update UML for storage classes
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#124 Add skills to the Group model and storage
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
Labels: enhancement

#152 Modify deleteCourseMate to also delete all instances in the GroupList
  src/main/java/seedu/address/model/GroupList.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: bug
